# Generated by Django 5.2.3 on 2025-06-29 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
