# Generated by Django 5.2.3 on 2025-06-23 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='content',
            field=models.TextField(help_text='日記の内容を入力してください（長文可）', verbose_name='本文'),
        ),
        migrations.AlterField(
            model_name='diary',
            name='title',
            field=models.CharField(help_text='日記のタイトルを１００文字以内で入力してください', max_length=100, verbose_name='タイトル'),
        ),
    ]
